[package]
name = "esp-wifi-rs"
authors = ["Todor Todorov <todor@peychev.com>"]
resolver = "2"
version = "0.1.0"

[dependencies]
anyhow = "=1.0.81"
esp-idf-svc = "=0.48.1"
log = "=0.4.21"

[build-dependencies]
embuild = "=0.31.4"

[dev-dependencies]
toml-cfg = "=0.1.3"
